### ISSUE TITLE
Debugger Plugin not being built into JS Tracker - More detailed instructions

### ISSUE THREAD

**Issue by markojak** [snowplow/snowplow-javascript-tracker#1000]
**Describe the bug**
When modifying the tracker configuration file to enable the Debugger Plugin and then running the rush build it does not automatically bundle the Debugger into the new build. It seems that further code is missing from src/features.ts and src/configurations.ts

**To Reproduce**
Modify `./trackers/javascript-tracker/tracker.config.ts` to contain ` Debugger: true,`

**Expected behavior**
Building the tracker would create a new sp.js with the Plugin Debugger included. 

**Additional context**
Debugger Plugin is not bundled in with the current open source version of the tracker that is released by this project.

**Comment by paulboocock** [comment]
So I never really anticipated people wanted to bundle the debugger plugin directly into `sp.js` because I didn't think you'd want to push the debugger to production, only use it locally for testing. 

You can dynamically load plugins at runtime, which is how I thought the debugger would always be used:

```javascript
window.snowplow('addPlugin', 
  "https://cdn.jsdelivr.net/npm/@snowplow/browser-plugin-debugger@latest/dist/index.umd.min.js",
  ["snowplowDebugger", "DebuggerPlugin"]
);
```

One challenge with bundling it directly is setting the LOG_LEVEL parameter when initialising the Plugin. It could be done inside `tracker.config.js` but then this changes the current format as we'd probably need to introduce an object like `debugger: { log_level: 'debug' }` or something similar. 
By dynamically adding the plugin, you can inject the plugins parameters:

```javascript
window.snowplow('addPlugin', 
  "https://cdn.jsdelivr.net/npm/@snowplow/browser-plugin-debugger@latest/dist/index.umd.min.js",
  ["snowplowDebugger", "DebuggerPlugin"],
  [ 4 ] // 4 = Info logs
);
```

See here for docs: https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/javascript-tracker-v3/plugins/debugger/

**Comment by markojak** [comment]
Hey @paulboocock Thanks for replying to this one. It's a good point - I think the core of the issue is that we cannot curently dynamically load the plugin due to our implementation.
We have Snowplow implemented through [GetAnalytics Plugin ](https://getanalytics.io/plugins/snowplow/)

 The issue is then rather how do we selectively load this plugin with our current wrapper. On second thought this then sounds like more of "our problem" than a relevant issue for this repo.

Any final thoughts or assistance would be appreciated though,

The way that additional Plugins that ship with sp.js are loaded right now is: 

```
analytics.on('initialize:snowplow', ({ instance }) => {
  instance.plugins.snowplow.enableActivityTracking(10, 10)
  instance.plugins.snowplow.enableLinkClickTracking()
})
```

The full load here:

```
const analytics = Analytics({
  app: 'awesome-app',
  plugins: [
    // Minimal recommended configuration
    snowplowPlugin({
      name: 'snowplow',
      scriptSrc: '//*.cloudfront.net/2.17.0/sp.js',
      collectorUrl: 'collector.mysite.com',
      trackerSettings: {
        appId: 'myApp',
        contexts: {
          webPage: true
        }
      }
    })
  ]
})
```

**Comment by paulboocock** [comment]
Ah yes, it's on my radar to bump the getanalytics.io plugin to v3. I actually started it last week but haven't had time to finish it yet. 

The plugins don't work with v2 of the tracker, and the getanalytics.io plugin only works with v2 at the moment. Since v3 is already an npm package (@snowplow/browser-tracker) it hasn't been a high priority to update this to v3.

**Comment by paulboocock** [comment]
This has now been updated in the @analytics package. 

https://github.com/DavidWells/analytics/issues/202
