### ISSUE TITLE
Page ping events doesn't send on tab in focus

### ISSUE THREAD

**Issue by denisov-vlad** [snowplow/snowplow-javascript-tracker#1056]
**Describe the bug**
From [documentation](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/javascript-tracker-v3/tracking-events/#activity-tracking-page-pings):

> If activity tracking is enabled, the web page is monitored to see if a user is engaging with it. (E.g. is the **tab in focus**, does the mouse move over the page, does the user scroll etc.)

I don't see any page ping events if tab in focus only. Am I misunderstood "tab in focus" meaning?

**To Reproduce**

1. Open web page with snowplow initialized (we use `minimumVisitLength: 5, heartbeatDelay: 5` settings)
2. Wait for first ping event in Network tab and move mouse from DevTools to web page content
3. Wait for 5 seconds and see 0 page ping events except first
4. Try to move mouse
5. See page ping event

**Expected behavior**
On step 3 expected ping event.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 15.1

**Additional context**
If there is an error in docs it could be my feature request: optionally turn on ping events when tab is in focus only and there is no explicit activity.

**Comment by paulboocock** [comment]
Just for clarity, a page ping will only fire if a tab is in focus, and the user has interacted with the page for the "heartbeat" (i.e. not first) page ping. The user has to have interacted (scrolled, moved the mouse around, filled in a form, clicked something) with the page within that heartbeat time period. So setting the value as a low number, like 5 reduces the chance of user interaction and for a heartbeat page ping to fire.

I'm not sure if moving your mouse from devtools over the web page will trigger any event handlers, it's likely browser dependent but I anticipate the devtools might have focus, rather than the actual page preventing the event handlers from firing. I can't replicate this with Firefox either way, doing as you say triggers a page ping for me on https://docs.snowplowanalytics.com/

![2022-01-28 11 24 01](https://user-images.githubusercontent.com/8820009/151538837-e847cd32-a4dc-481b-b898-32113d5bffe5.gif)

I only moved my mouse here, no other activity occured (clicks, scrolls, etc.).

I notice you raised this issue for Safari. Safari often opens the developer tools in a new window, not attached to the same tab in the browser (like in my firefox screen). Therefore the tab doesn't have focus. You'd have to click the browser to get that tab to be focused rather than the developer tools. I did test Safari with an attached dev tools though and it worked fine again:

![2022-01-28 11 35 04](https://user-images.githubusercontent.com/8820009/151540170-a0de8aea-fcb5-4388-8e10-c74a7a453212.gif)

**Comment by denisov-vlad** [comment]
Okay. I understood. 

The question was in sending page ping events even if user don't move mouse. Only tab is open and nothing happens.

I'm comparing with Piwik (Matomo) which is our current analytics frontend library and trying to find differences to make proper migration to Snowplow. Piwik sends event event if the cursor isn't moving.

https://user-images.githubusercontent.com/7091907/151544013-7b334758-11d5-46af-90f1-423a09dd199d.mov

**Comment by paulboocock** [comment]
Oh I see, but page pings are for activity tracking, thats what we're measuring here. It leads to a "Active time on page" metric in our web data model. I wouldn't say a in focus page with the user doing absolutely nothing consistutes as activity, however thats why I'd increase the window a little, say 15 or 30 seconds, particularly if dealing with typically long form content (like a blog post or something where users might be static for longer).

I don't particularly want to introduce a flag for this change in behaviour either, we're looking to simplify configuration where possible, configuring our trackers (particularly this one) has become increasingly complex.

However, if you would like this to happen, you could update activity tracking yourself if you want to match this behaviour. Calling `window.snowplow('updatePageActivity');` will tell the tracker there has been activity even when there has been none. I guess you could put this in a `setInterval` which continues triggering `updatePageActivity` every second or something as long as the users mouse is within the viewport.

Hopefully that covers your use case, I'm going to close this as a wont fix as I think that this behaviour deviates from our desired use case for activity tracking. I'm happy to continue discussing this though if you feel the above `updatePageActivity` API doesn't allow you to achieve what you need.

**Comment by denisov-vlad** [comment]
Thanks!

I think that Snowplow's implementation of ping events is better :)

> It leads to a "Active time on page" metric in our web data model. 
Got it. We use only Snowplow's client trackers with self-written backend (Python + ClickHouse) so I didn't think about it.
