### ISSUE TITLE
Not able to track events

### ISSUE THREAD

**Issue by bhavik-mtech** [snowplow/snowplow-javascript-tracker#1199]
Not able to track any events using nodeJs. Here is sample code 

const e = gotEmitter(
    'end-point.app.try-snowplow.com', // Collector endpoint
  );

const t = tracker([e], 'myTracker', 'myApp', false);

t.track(snowplow.buildPageView({ 
    pageUrl: 'http://localhost:3000', 
    referrer: 'http://test.com'
  })
);

Is there any way to get error or access log using that we can identify issues?

**Comment by matus-tomlein** [comment]
Hi @bhavik-mtech,

You might need to call `e.flush()` if you only track one event. It's because the tracker buffers events and sends them in batches (if using POST requests – default) to reduce the number of requests. The default buffer size is 10, so the tracker would wait for 10 events to buffer up before making a request. By calling flush, you force it to make the request sooner.

The tracker does not have logging yet, but you can make use of the callback in the `gotEmitter` to be notified about the failed or successful requests, [set the docs here](https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/javascript-trackers/node-js-tracker/node-js-tracker-v3/initialization/#configure-emitter).
