### ISSUE TITLE
Type of addGlobalContexts does not accept arrays

### ISSUE THREAD

**Issue by Mookiies** [snowplow/snowplow-javascript-tracker#1380]
**Describe the bug**
The type from the docs lists `addGlobalContexts` as taking an array of contexts for its "tag". Here: https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/javascript-trackers/web-tracker/custom-tracking-using-schemas/global-context/#named-global-entities

Specifically this is a type error

```ts
// add the entity defined by `globalContextDefinition` with the name "example"
var globalContextDefinition = [ruleSet, contextEntityToAdd];
addGlobalContexts({ example: globalContextDefinition }); 
```

However this a type error because the signature of `addGlobalContexts` is

```ts
  contexts:
    | Array<ConditionalContextProvider | ContextPrimitive>
    | Record<string, ConditionalContextProvider | ContextPrimitive>
```

If were to match the docs it would need to be 

```ts
  contexts:
    | Array<ConditionalContextProvider | ContextPrimitive>
    | Record<string, Array<ConditionalContextProvider | ContextPrimitive>>
```

**To Reproduce**
```ts
      const context = {
        schema: 'iglu:io.augur.snowplow/identity_lite/jsonschema/1-0-0',
        data: {
          foo: 'bar',
        },
      };

      addGlobalContexts({ example: context }); // No error
      addGlobalContexts({ example: [context] }); // TS-error: type is not assignable to type ConditionalContextProvider | ContextPrimitiv
```

**Expected behavior**
Can add named context in array form

**Tracker Version**
 "@snowplow/browser-tracker": "npm:^4.0.2"

**Comment by jethron** [comment]
Thanks for the report @Mookiies!

I don't think I see the docs issue here; the `[ruleSet, contextEntityToAdd]` example is the type `ConditionalContextProvider`: it is a single [`RuleSetProvider`](https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/javascript-trackers/web-tracker/custom-tracking-using-schemas/global-context/#conditional-context-providers) value, _not_ a `ContextPrimitive[]`.

It's a bit clunky, but you should be able to have multiple primitives with a single tag by specifying a no-op filter to make it satisfy `ConditionalContextProvider`:

```typescript
      const context = {
        schema: 'iglu:io.augur.snowplow/identity_lite/jsonschema/1-0-0',
        data: {
          foo: 'bar',
        },
      };

      addGlobalContexts({ example: context }); // No error
      addGlobalContexts({ example: [() => true, [context]] }); // No error
```

Is that a workable alternative for you?

Otherwise it's a bit more than just a type change but we can look at supporting this directly as well.

**Comment by Mookiies** [comment]
Thanks you @jethron I didn't understand that you could have a no-op rule set. This solves my use-case! 

---

FWIW my use case is having a wrapper that matches the react-native tracker API to the browser tracker. This is why I've got the array because in RN it's 

```ts
tracker.addGlobalContexts({
    tag: 'my-new-tag',
    globalContexts: [
        {
            schema: 'iglu:com.snowplowanalytics.snowplow/ad_impression/jsonschema/1-0-0',
            data: {impressionId: 'my-ad-impression-id'},
        },
    ]
});
```

`addGlobalContexts({ [gc.tag]: [() => true, gc.globalContexts] });` is totally workable. Thank you 🙏
