### ISSUE TITLE
Session handling issue with Browser Tracker V4

### ISSUE THREAD

**Issue by davidher-mann** [snowplow/snowplow-javascript-tracker#1381]
**Describe the bug**
Significant increase in "artificial" sessions:
- consecutive sessions within less than 600 milliseconds
- most session have just 1 event, the majority zero page_views 
- Sessions from legitimate users, definitely not bots

First assumption: Maybe the issue is caused the new async cookie writes.

**To Reproduce**
Not clear if it can be reproduced, but very likely:
1. Use a Browser tracker version 4 (4.0.1  or 4.0.2) in production, initialize the tracker with keepalive: true
2. Check you modeled event data and search for session with only one event see query below.

_Disclaimer: this query only works with our data model, it is only an example to adapt the query to other data models:_
```SQL
WITH PREP_Sessions_Details AS (
SELECT
  DATE(StartTstampUTC) AS SessionStartDate,
  S.StartTstampUTC,
  S.EndTstampUTC,
  TIMESTAMP_DIFF(S.EndTstampUTC, S.StartTstampUTC, SECOND) AS SessionDuration_inSeconds,
  -- Calculate the time between the sessions of a NetworkUserId
  TIMESTAMP_DIFF(
    S.StartTstampUTC, 
    LEAD(S.StartTstampUTC, 1) OVER (PARTITION BY S.NetworkUserId ORDER BY StartTstampUTC DESC), MILLISECOND
  ) AS TimeBetweenSessions_inMilliSeconds,
  S.NetworkUserId,
  LEAD(S.NetworkUserId, 1) OVER (PARTITION BY S.NetworkUserId ORDER BY StartTstampUTC DESC) AS PreviousNetworkUserId,
  S.DomainSessionId,
  S.DeviceAndBrowserDetails.DeviceClass,
  S.DeviceAndBrowserDetails.AgentName,
  S.PageViews, -- PageViews per Session
  S.Events -- Events per Session
FROM
  `<<session_table>>`
WHERE TRUE
  AND DATE(S.StartTstampUTC, "Europe/Zurich") >= "2024-11-11"
  AND S.NetworkUserId IN (
    -- find all NetworkUserIds that have only one event and no page views, channel: direct
    SELECT
      NetworkUserId
    FROM
      `<<session_table>>`
    WHERE TRUE
      AND DATE(StartTstampUTC, "Europe/Zurich") >= "2024-11-12"
      AND TrafficAttributionChannel_Array[SAFE_OFFSET(0)].TrafficAttributionChannel.Level1 = "Direct"
      AND PageViews = 0
      AND Events = 1
  )
GROUP BY
  ALL
)

SELECT
  *,
  COUNT(DISTINCT DomainSessionId) OVER(PARTITION BY NetworkUserId, SessionStartDate) AS NumberOfSessionsPerDayAndUser
FROM
  PREP_Sessions_Details  
WHERE TRUE
-- only show consecutive sessions of the same networkuserid and the time between the sessions is less than 1 second or null to catch the first session
  AND (TimeBetweenSessions_inMilliSeconds < 1000 OR TimeBetweenSessions_inMilliSeconds IS NULL)
QUALIFY
-- only show users that have at least 2 sessions per day
  NumberOfSessionsPerDayAndUser >= 2
ORDER BY
  NetworkUserId,
  StartTstampUTC
```

**Expected behavior**
Consecutive sessions that are only milliseconds apart should only occur very rarely.

**Screenshots**
<img width="1432" alt="Issue Query and Viz" src="https://github.com/user-attachments/assets/fea622f8-835a-491d-8b3c-b42130a7aec1">

**Desktop (please complete the following information):**
Mostly Firefox 132, Desktop, but also Chromium Browser

**Additional context**
We deployed tracker version 4.0.1 on Monday for multiple hours, then rolled back due to [this issue](https://github.com/snowplow/snowplow-javascript-tracker/issues/1376)

The above described issue did not happen before the deployment of 4.0.1, but also happend in version 4.0.2. 

Options to isolate the issue:
- Just in case it is caused by the new async cookie writes: create a temporary tracker Initialization option to disable / enable async cookie writes
- A test which we could run in theory: set keepalive to false to make sure this is not the issue.

Unfortunately we had to revert tracker version V4 again, due to the increase in "artificial" sessions sessions.

PS: please test the next release on your own websites! Neither snowplow.io, nor discourse.snowplow.io, iglucentral.com or docs.snowplow.io is running Browser Tracker V4. console.snowplowanalytics.com is still on Version 4.0.0 (which has the event queue issue in Chromium).

**Comment by matus-tomlein** [comment]
Thank you for reporting this and for the detailed write up @davidher-mann!

It does appear to be an issue due to the async cookie writes. I don't think it's likely that it has anything to do with the `keepalive` setting as the network requests are decoupled from the session updates.

It could be that users open the website in two or more tabs at once causing a race condition. We already identified this problem with respect to the `client_session.eventIndex` being more likely to have duplicate values, but considered it a valid tradeoff for the performance gains and tried to minimize it. These artificial sessions are a bigger issue though.

We will try to reproduce this and address. One option that comes to mind is to make the first session cookie update synchronous (keeping the subsequent cookie updates in the session async). This should only have a small performance impact since it will only need to be done once per session.

One thing that is puzzling me in your data is why such a big increase on Firefox compared to the other browsers, will try to do more tests on Firefox in case there is some other issue.

Worth mentioning as a workaround for anyone seeing this issue that there is an option in the tracker to make cookie handling synchronous to reflect the behaviour in v3, [see docs here](https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/javascript-trackers/web-tracker/configuring-how-events-sent/#synchronous-cookie-writes).

Also fair point on updating the tracker version to the latest on our websites, we will work on this internally.

**Comment by matus-tomlein** [comment]
Just an update – we have published a fix for this in the 4.0.3 release. We are working on getting the release published on our websites and will compare the data with the v3 tracker.

**Comment by davidher-mann** [comment]
Hi @matus-tomlein are you able to provide an update this week if you found issues with the new version 4.0.3 on Snowplow websites?

**Comment by matus-tomlein** [comment]
Hi @davidher-mann, we have had the 4.0.4 version deployed on the docs and website for around 5 days. Looking at the daily number of sessions, average and median duration, I don't see a significant difference from the weeks before. It looks like the data hasn't really changed since we upgraded the tracker version, so hopefully this problem with artificial sessions has been resolved.
