### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#154]
The general idea for integration tests:

* Run them in Sauce Labs
* Run a node.js server as a mock Snowplow Collector
* Point the Snowplow JS Tracker to the mock Snowplow Collector
* Fire events from the Snowplow JS Tracker
* Verify the payload sent to the mock Snowplow Collector

**Comment by alexanderdean** [comment]
@fblundun - can you update this ticket with what you have tried and what is not working?

**Comment by fblundun** [comment]
Just installing Mountebank by adding the line

```
install:
 - npm install -g mountebank --production
```

to .travis.yml causes the error `Fatal error: Unable to find local grunt.`

(See [the failing build](https://travis-ci.org/snowplow/snowplow-javascript-tracker/builds/48616527) and [the commit which fixed it](https://github.com/snowplow/snowplow-javascript-tracker/commit/e209974c9bdaef4d4c3509f5dfa176f0dba0697c))

**Comment by alexanderdean** [comment]
Mountebank tests in our PHP Tracker: https://github.com/snowplow/snowplow-php-tracker/blob/master/.travis.yml

**Comment by fblundun** [comment]
There are a couple of practical problems using Mountebank:

- We don't know how to send an image in response to the tracker's GET requests, which prevents the tracker from sending more than one event
- In order to verify that requests sent by the tracker actually conform to expectations, we must examine the Mountebank logs

Instead we can use a simple server which will respond correctly and write the incoming requests to a log file in a more easily parsed format.

**Comment by alexanderdean** [comment]
Sounds good Fred - please update tickets etc accordingly!
