### ISSUE TITLE
Add --whitelabel option to build process

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#161]
_was_: **Add script manager as optional tag approach**

As in part of build etc.

**Comment by paulboocock** [comment]
This will be partially resolved by moving to ES Modules are users will directly import the tracker into their codebase rather than loading the script. However, for those still loading via a script the whitelabel option to create a different namespace queue seems easiest to fix this. We can consider this with V3 and the new rollupjs build process.

**Comment by dcarniel-evorra** [comment]
We're facing a similar issue when using the javascript tracker for our project. As we integrate it on different websites, we came across one that used v2 of the snowplow javascript tracker.

It caused issues which we tracked down to having the same `window.GlobalSnowplowNamespace` variable used by both versions.

Being able to build our own instance with such a "whiteLabel" option to change this global variable could work (we've done the change manually and it works but we'd rather have a properly built one ;-) ).

We'd be happy to contribute the change for the next release if that is still in the plans (and we manage to do it properly of course :-P )
