### ISSUE TITLE
Make domainUserId a UUID

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#274]

**Comment by alexanderdean** [comment]
See also: https://github.com/snowplow/snowplow-actionscript3-tracker/issues/21

**Comment by fblundun** [comment]
If we don't want to break the pipeline for people who haven't upgraded to the latest table definition (with the increased domain_userid field size), we could do this in two steps: to start with we could generate a proper uuid and drop all but 16 characters of it. I think this would still be higher entropy than the current implementation (a hash of browser features and the timestamp to the nearest second), but would have to check the uuid generation method to be sure.

**Comment by alexanderdean** [comment]
That will be the de facto behaviour anyway I think if someone hasn't upgraded their Redshift - the domain_userid value will get truncated at 16 characters.

I think when we release this in the 3.0.0 we should push people to upgrade their Redshift at the same time, so there is only one breakage in user IDs (old to UUID), rather than two breakages (old to truncated UUID to full UUID)...

**Comment by fblundun** [comment]
We don't necessarily need a breakage at all - we could just keep the old user IDs when they are available in the ID cookie and generate a new UUID otherwise.

**Comment by alexanderdean** [comment]
Ah - I like it!

**Comment by alexanderdean** [comment]
Bringing forwards following Augur analysis

**Comment by alexanderdean** [comment]
Bringing forwards as we should get on with this...
