### ISSUE TITLE
Whitelist or blacklist specific forms

### ISSUE THREAD

**Issue by ryanrk** [snowplow/snowplow-javascript-tracker#287]
There are some forms we may not want to track like password forms, credit cards, addresses and may want to exclude them.  If we enable form tracking on a page we should have a way to to either whitelist or blacklist certain forms by either class name, id or some sort of attribute.

**Comment by fblundun** [comment]
For link click tracking, you can have either a whitelist of links to track, a blacklist of links not to track, or a filter function which determines which links to track. We could have something similar for both forms and fields. For example this

```javascript
{
  forms: {
    filter: function (elt) {return elt.id === "formToTrack"}
  },
  fields: {
    blacklist: ["password", "address"]
  }
}
```

would track every field other than password and address in all forms with ID "formToTrack".

One flaw in this API is that if you have two forms with "address" fields, it is difficult to blacklist the address field in only one of them.

**Comment by alexanderdean** [comment]
This looks good. Can you clarify what the argument is to the filter function?

**Comment by fblundun** [comment]
The argument to the filter function is either the form element under consideration or the field element under consideration.

So 

```javascript
{
  forms: {
    filter: function (elt) {return elt.id === "formToTrack"}
  },
  fields: {
    filter: function (elt) {return elt.name !== "password"}
  }
}
```

would track every field in the form with ID "formToTrack" whose name is not "password".

Whitelisting for fields would probably work differently than whitelisting for forms or links. With links and forms a whitelist is a list of HTML classes such that only elements with one of those classes are tracked. With fields it might make more sense to whitelist based on field name rather than field classes.

(And a similar statement holds true for blacklisting.)

**Comment by alexanderdean** [comment]
Understood. Why the opting for names vs classes for fields?

**Comment by fblundun** [comment]
Usually field elements in forms are identified by their `name` property: http://www.w3schools.com/tags/att_form_name.asp

We could use classes instead, but I think people are more likely to already have fields with the `name` property.

**Comment by alexanderdean** [comment]
Sounds good to me - thanks @fblundun !

**Comment by fblundun** [comment]
The way I implemented this makes a breaking change to the form tracking API because the position of the context argument has changed: https://github.com/snowplow/snowplow-javascript-tracker/commit/fe84b37bffece671dccd561fee4d0c133e807b85#diff-862f48f6fbba902dce9286abfa48db47L1026

**Comment by alexanderdean** [comment]
Okay Fred - thanks for the heads-up...
