### ISSUE TITLE
Generate a unique session ID for each new session

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#347]
Not to replace, but live alongside `domain_sessionidx`.

Users would then be free to pick which they used in the data modeling stage downstream.

**Comment by fblundun** [comment]
Would this be its own querystring parameter, or part of a context?

**Comment by alexanderdean** [comment]
This will be part of a new client_session I think, which we will:

1. Use for Android and iOS
2. Slowly port the JS Tracker fields into

**Comment by alexanderdean** [comment]
Arg, we already have a field for this in atomic.events. Sorry I was wrong

**Comment by alexanderdean** [comment]
https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentManager.scala#L121

**Comment by fblundun** [comment]
Of course!

**Comment by alexanderdean** [comment]
We can still port it into the client_session context later...

**Comment by fblundun** [comment]
I'm storing this as another value in the domain user ID cookie. It gets recomputed every time the session cookie is found to not exist.

**Comment by fblundun** [comment]
My current approach:

Whenever the page loads or an event is fired, if the session cookie exists and the sessionId part of the ID cookie exists, use the existing sessionId in the ID cookie; otherwise overwrite the sessionId with a new random UUID.

How should the sessionId work if cookies are disabled?

With my current approach a new sessionId is generated for every event.

An alternative would be to persist the sessionId until the user leaves the page (i.e. give it the same lifespan as the page view UUID in #369). This is also how the domainUserId works if cookies are disabled.

This alternative approach actually wouldn't be fully consistent with how we normally increment sessions - no matter how long a user is inactive on a page, the sessionId won't change.

**Comment by fblundun** [comment]
Clarification:

## Current approach:
#### Cookies disabled:
sessionId is regenerated for every event

#### Cookies enabled:
sessionId is regenerated whenever an event fires and it has been 30 minutes since the last event

### Alternative approach:
#### Cookies disabled:
sessionId is generated on page load and doesn't change as long as the user is on the page  (but is different in different tabs)

#### Cookies enabled:
sessionId is regenerated whenever an event fires and it has been 30 minutes since the last event

## How session count works

#### Cookies disabled:
session count is always 1

#### Cookies enabled:
session count increases whenever an event fires and it has been at least 30 minutes since the last event

**Comment by bogaert** [comment]
If cookies are disabled, I think the alternative approach makes most sense. If the page view event has a different sessionId than the subsequent page pings, this will create additional complexity in the data modeling.

**Comment by alexanderdean** [comment]
I agree - a client session should try to use the most durable local state it can find. In terms of local state, cookie > JavaScript variable > stateless, where stateless would be a new UUID each event.

**Comment by ryanrozich** [comment]
quick question on this:

> sessionId is regenerated whenever an event fires and it has been 30 minutes since the last event

this seems to indicate that, if a user is on a page, then pauses activity for 30min and comes back there would be one session id for the events (page_view, page_pings, and other) before the pause and a different session id for events sent after the comes back to the page. 

This might make data modeling a little more complicated, since some page views (web_page context ids) could belong to multiple sessions but the events associated with those views would be bifurcated between sessions. 

Could you clarify if this is correct?

**Comment by yalisassoon** [comment]
Hi @ryanrozich - I believe your description is absolutely correct. What that means is that if a user loads a page page on a tab in their browser, then disappears for e.g. 45 minutes, then returns to the tab, a page ping event will fire with a page view ID that's associated with a page view event from the previous session, but the page ping event will be the first event in a new session.
