### ISSUE TITLE
Create browser plugins context

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#367]
This would contain a hash of all plugins, together with boolean values for plugins specified by a user via a filter function

**Comment by paulboocock** [comment]
This borderlines on fingerprinting technology which we know is inconsistent at best and does not sit well with the current trend towards protecting a users privacy.
If a user wishes to do this, I would advise they create the loagic themselves and attach as a global context rather than the tracker having this concept built in.
