### ISSUE TITLE
Passing along a function instead of a context

### ISSUE THREAD

**Issue by wiremine** [snowplow/snowplow-javascript-tracker#372]
I'm running into an issue where I need to update a set of contexts dynamically per ping, instead of once when trackPageView is called:

When a website uses something like ajaxify [1], the contexts are not reset when a URL is updated. So, it is sending along incorrect data on subsequent page pings. 

My naive solution is to pass along a function to trackPageView, instead of (or alongside) the context param. logPageView() would call the function to generate contexts. heartBeat() would also call this. 

Code would look something like this:

```
function logPageView(customTime, context, contextCallback) {
    var dynamic_context = contextCallback();
    context.push(dynamic_context);
    // later, inside heartBeat()
    logPagePing(pageTitle, context, contextCallback);
       
}
```

In regards to ajaxify, contextCallback() could check if the URL had changed, and refresh the context. (I.e., if the URL changes, the function would re-generate the contexts for the new URL).

Wondering a) if this has been discussed before, and/or b) if there is a better way to handle this use case. 

Happy to work on a Pull Request given the right direction. 

[1] https://github.com/browserstate/ajaxify/blob/master/ajaxify-html5.js

**Comment by alexanderdean** [comment]
Sounds like a practical solution to me. @yalisassoon, @fblundun thoughts?

**Comment by fblundun** [comment]
This seems good. To be more general, the contextCallback argument could be an array of functions for if you have multiple dynamically updated contexts.

**Comment by alexanderdean** [comment]
Makes sense. I'd suggest probably a supplementary argument, so that we don't have to check the array contents for strings or functions

**Comment by fblundun** [comment]
(By the way, in the current version of the tracker, if you mutate the contexts array between the page view and a page ping, the changes will be reflected in the event. But the callback solution works in more situations.)

**Comment by fblundun** [comment]
My above approach is actually a bit inflexible. The number of contexts attached to each page ping is always equal to the length of the array of context-generating functions, since there is always exactly one context per function. It's conceivable that you would want the number of contexts generated to be determined dynamically, so maybe we should instead have a single function which can return an arbitrarily long (and possibly empty) array of contexts?

(Or for maximum flexibility we could let people have an array of functions, each of which returns an array of contexts, and then flatMap those contexts. But that might be overcomplicating things.)
