### ISSUE TITLE
Support for tracking all DOM events?

### ISSUE THREAD

**Issue by lpgeiger** [snowplow/snowplow-javascript-tracker#376]
Not sure if I missed this in the docs.
Is there a way to have the javascript tracker emit events for all the DOM events? Or at least all the mouse click events?
I see that you can do specific events, but I want to capture all events and analyze ad hoc.

**Comment by alexanderdean** [comment]
Interesting idea, but that's not supported currently...

**Comment by keyscores** [comment]
OK thanks. Another related issue: I'm not getting all the custom structured events to fire. I'm calling snowplow(trackStructEvent) on a button click but i'm only getting the pageview, pv, data. How can I check that the custom structured events are firing?

**Comment by alexanderdean** [comment]
Can you direct support requests to the Google group please: https://groups.google.com/forum/#!forum/snowplow-user

**Comment by keyscores** [comment]
Could the click 'enableActivityTracking' be expanded to include a few other elements besides <a>?

**Comment by alexanderdean** [comment]
If there's activity which is missing from enableActivityTracker, yes we should definitely add it! Can you let us know what's missing?

**Comment by keyscores** [comment]
Hi Alex, I wrote you on the google groups. I'd like to see all click events for <button> , <select> for example.  <img>  would be good as well for edge cases. I'm guessing it would be easier to track all clicks regardless of tag.

**Comment by alexanderdean** [comment]
Added #402

**Comment by paulboocock** [comment]
Closing this in favour of more specific #402. Tracking all DOM events would be very noisy and not something I'd expect the JS Tracker to support out of the box. It could certainly be implemented with the JS Tracker, by using the standard `track...` methods and custom DOM tracking code, but due to how infrequently this functionality would be required it makes sense to educate users on how to achieve this if they need it.
