### ISSUE TITLE
If no GA cookies are present, should we still attach the empty GA cookie context?

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#384]

**Comment by alexanderdean** [comment]
Hmm, good question

**Comment by paulboocock** [comment]
If you have turned on gaCookie context for an app-id then the fact that there is no context for an event should be enough to suggest that it is missing because there is no cookies. Attaching an empty context only leads to bloat the payload further (it's already pretty big!). Closing unless anyone feels differently.
