### ISSUE TITLE
Add setting to automatically use top-level domain for duid

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#409]
At the moment, choices for the duid are:

1. Automatically use the full domain e.g. `foo.acme.co.uk`
2. Manually specify a higher-level domain e.g. `.acme.co.uk`

Is there a way we could **automatically** specify a higher-level domain like `.acme.co.uk`? In other words, we would not have to manually specify the domain but rather it would be auto-detected.

Not a biggie because tag managers make option 2 fairly easy but still would be nice to have.

**Comment by fblundun** [comment]
According to [this](https://developers.livechatinc.com/blog/setting-cookies-to-subdomains-in-javascript/), the only way to get the top-level domain is to try setting cookies on increasingly specific subdomains until one of them works.

e.g. `.uk` fails, `.co.uk` fails, but `bbc.co.uk` succeeds.

**Comment by alexanderdean** [comment]
Fun fact, the Chromium source has a list of "registry controlled domains":

```
$ grep -r "com\.cy" .
./components/domain_reliability/bake_in_configs.py:  'google.com.cy',
./components/domain_reliability/baked_in_configs/star_google_com_cy.json:  "monitored_domain": "*.google.com.cy",
./net/base/registry_controlled_domains/effective_tld_names.dat:com.cy
./net/base/registry_controlled_domains/effective_tld_names.dat:blogspot.com.cy
./net/base/registry_controlled_domains/effective_tld_names.gperf:blogspot.com.cy, 4
./net/base/registry_controlled_domains/effective_tld_names.gperf:com.cy, 0
./net/http/transport_security_state_static.json:    { "name": "google.com.cy", "include_subdomains": true, "pins": "google" },
./tools/perf/page_sets/alexa1-10000-urls.json:  "http://www.google.com.cy/",
```

**Comment by alexanderdean** [comment]
Bringing forwards...

**Comment by fblundun** [comment]
I wrote a gist which does this: https://gist.github.com/fblundun/59119a987bf4e8c934f2

**Comment by fblundun** [comment]
We shouldn't make the root domain discovery the default because it will break things for people who have already been setting cookies on the subdomain.

**Comment by alexanderdean** [comment]
Yes good point, I think we need some kind of flag value or equivalent to specifically enable it

**Comment by fblundun** [comment]
How about asking people to put

```js
discoverRootDomain: true
```

in their tracker configuration?

**Comment by alexanderdean** [comment]
I like!

**Comment by bernardosrulzon** [comment]
@fblundun I tried this new feature, but noticed that the domain hash that gets appended to _sp_id and_sp_ses is different than what is generated by manually setting the cookie domain to `.my domain.com`. This would end up generating different domain_userids for the same user and reset session counting, right? Is that expected behavior?

**Comment by fblundun** [comment]
@bernardosrulzon - well spotted! This happens because the logic which finds the root domain is returning "mydomain.com" instead of ".mydomain.com". (The library we use for setting cookies doesn't care about the difference.) This is why the domain hash is different.

This issue should only come up for people who have been manually setting the subdomain with the leading "." but want to start doing it automatically. I think the simplest solution is just recommending that people in that situation keep doing it manually instead of using enabling this feature.

**Comment by alexanderdean** [comment]
Makes sense - I agree with @fblundun's workaround - @jbeemster please can you add a warning into the 2.6.0 documentation?

**Comment by jbeemster** [comment]
Updated here: https://github.com/snowplow/snowplow/wiki/1-General-parameters-for-the-Javascript-tracker#2219-automatically-discover-and-set-the-root-domain
