### ISSUE TITLE
Update GTM implementation guide with instructions for mirroring GA enhanced ecommerce in Snowplow

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#416]
Note that this depends on the different com.google.analytics.enhancedecommerce schemas being added to Iglu central first.

Once this is done, we should be able to update the guide to explain what combination of trackUnstructEvent calls with the appropriate custom contexts can be setup in GTM to send the Enhanced Ecommerce data available in the dataLayer as documented [here](https://developers.google.com/tag-manager/enhanced-ecommerce#data-layer) into Snowplow

**Comment by alexanderdean** [comment]
@fblundun - could you do a first pass at this?

For each tag we'd need to have the custom HTML that you'd insert in the tag, which is the unstruct event call with the context and a firing rule based on what is present in the dataLayer.

You'd have to map the objects in the dataLayer to the custom context / unstructured event.

Please speak to @yalisassoon if anything is unclear!

**Comment by yalisassoon** [comment]
@fblundun - just to add to @alexanderdean comment above, we'd need brief instructions on:

1. Creating the relevant variables in the tag manager. I expect one variable for each object in the GTM dataLayer e.g. one for the `ecommerce.impressions` array, one for the `ecommerce.click` object, one for the `ecommerce.detail` object, one for the `ecommerce.currencyCode`, one for the `ecommerce.add`, one for the `ecommerce.remove` and one for `ecommerce.promoView`. Note that the objects in the dataLayer are specified [here](https://developers.google.com/tag-manager/enhanced-ecommerce). Each variable you create is a `dataLayer` variable, and corresponds to an object in the dataLayer. Once you've done this, you can 'access' the different objects in the dataLayer by inserting `{{ my_variable_name }}` in the custom HTML / JS code on each tag.
2. Create a trigger for each tag. For example, a rule that fires a tag when a promotion click occurs when `event = promotionClick`
3. Create a relevant tag for each of the five events. This should include the custom HTML that would need to be pasted in and the firing rule setup in (2) that would need to be selected. The custom HTML would contain the different variables defined in (1).

Does that all make sense? I'll be in tomorrow by midday so can discuss in person if helpful.

Thanks!

**Comment by fblundun** [comment]
This is what I have so far. To make it easier to implement (less copy and pasting) I have used one trigger, one data layer variable, and one tag. In this example the tag also has sets up Snowplow and does page view tracking - since the tag fires on every page load, I didn't see any reason not to move the page view tracking there.

The enhanced ecommerce trigger: `checkout|checkoutOption|productClick|addToCart|removeFromCart|promotionClick` with regex matching enabled. (Probably there are more things to add to the regex - these are all the event types from the example page [here](https://developers.google.com/tag-manager/enhanced-ecommerce).)

The GTM data layer variable is called `ecommerce`.

The tag, configured to fire on any page view and on the enhanced ecommerce trigger defined above: https://gist.github.com/fblundun/6ef375ec777b4a729f7a

When the page initially loads, the tag loads, loads Snowplow, does whatever page view tracking you want, then checks the ecommerce data layer variable. This is for enhanced ecommerce data added to the data layer without an `"event": xxx"` field. (It is necessary to ensure that this data is added before the tag fires - the GA documentation says to use the firing rule "{{event}} equals gtm.dom". So we should recommend using that as the trigger instead of "any pageview".) If it exists, the tag fires an unstructured event. Every time a dataLayer.push has an event matching the regex, the tag fires another unstructured event.

One thing to 

What do you think?

**Comment by alexanderdean** [comment]
Unterminated sentence near the end - "One thing to"

**Comment by yalisassoon** [comment]
Looks great @fblundun ! Elegant implementation!

If you can update the documentation with an implementation guide (setup variable, setup trigger, setup tag), that'd be ACE! I'll share it immediately with the loyalytics team

**Comment by fblundun** [comment]
I've added a wiki page here: https://github.com/snowplow/snowplow/wiki/Integrating-Javascript-tags-with-enhanced-ecommerce

The warning at the top of the page is due to the tables and schemas for the enhanced ecommerce events not yet being deployed.

**Comment by yalisassoon** [comment]
Hi Fred,

The page looks awesome!

Any chance we can add three screenshots - one for the variable, another for
the trigger and a third for the tag?

Thanks,


Yali

On Wed, Oct 21, 2015 at 3:59 PM, Fred Blundun <notifications@github.com>
wrote:

> I've added a wiki page here:
> https://github.com/snowplow/snowplow/wiki/Integrating-Javascript-tags-with-enhanced-ecommerce
>
> The warning at the top of the page is due to the tables and schemas for
> the enhanced ecommerce events not yet being deployed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow-javascript-tracker/issues/416#issuecomment-149923857>
> .
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>

**Comment by fblundun** [comment]
I've added the screenshots!

**Comment by alexanderdean** [comment]
Wow looks great!

**Comment by yalisassoon** [comment]
Awesome! Thanks @flbundun!

On Fri, Oct 23, 2015 at 12:03 PM, Alexander Dean <notifications@github.com>
wrote:

> Wow looks great!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow-javascript-tracker/issues/416#issuecomment-150544240>
> .
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>

**Comment by fblundun** [comment]
This is done, closing...
