### ISSUE TITLE
Add configurable max GET request size in bytes attribute

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#449]
Unfortunately it isn't possible to tell from JavaScript whether the GET response had status code 414 ([source](http://stackoverflow.com/questions/8108636/how-to-get-http-status-code-of-img-tags)). We could instead have a configurable maximum GET size to match the configurable maximum POST size.

Or maybe we should just tell people who are trying to send large events to use POST instead.

**Comment by sprsam** [comment]
Has there been any further examination of this? Attempting to implement some kind of error handling when a payload (_normally_ well under the GET limit) inadvertently includes too much/bad data.
Since we aren't able to receive the response status, we can't react to a bad event by removing it from localStorage. Playing around error event listeners didn't seem to help intercept/receive, unfortunately. Is there a suggested alternative? Currently considering checking the approximate size of a payload before making the call to sendEvent, but it seems like there should be a way to react to an error response from Snowplow.

**Comment by paulboocock** [comment]
We haven't investigated this much further, our current advice would be to switch the eventMethod to 'post' or 'beacon'.
