### ISSUE TITLE
Add documentation for the synchronous version of the tracker

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#501]
There's a working example of setting up the JS tracker syncronous here: https://github.com/snowplow/snowplow-javascript-tracker/blob/master/examples/web/sync.html.

However there is no formal documentation of this in the [usage manual](https://github.com/snowplow/snowplow/wiki/javascript-tracker).

We should add this documentation as part of this ticket.

**Comment by chuwy** [comment]
This is [documented](https://github.com/snowplow/snowplow/wiki/Integrating-Javascript-tags-onto-your-website#12-synchronous-integration) in Integrating JavaScript tags. However, I think we need to add one more warning note, because in very near future sync tracker [won't work](https://developers.google.com/web/updates/2016/08/removing-document-write) for all Chrome users with 2G or slow connections. Browser developers always were against this `document.write` practice.

In future I think we even could factor out [some legacy code](https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/snowplow.js#L217-L251) which is as far as I can see not documented anywhere and used only for sync tracker.

**Comment by chuwy** [comment]
This is done.
