### ISSUE TITLE
Check if browser has full support of Performance Timing API

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-javascript-tracker#539]
As per http://discourse.snowplowanalytics.com/t/events-going-to-bad-bucket/724

It seems that one of mobile browsers attaches `PerformanceTiming` context with invalid values.

Edit: correct link.

**Comment by chuwy** [comment]
From UA seems this is Android 4.2.2 browser.

**Comment by chuwy** [comment]
Samsung Galaxy Nexus Emulator 4.2 shows correct `window.performance` object (even though it shouldn't).

**Comment by alexanderdean** [comment]
Scheduling for the next release

**Comment by alexanderdean** [comment]
Bringing forwards as it's all related.

**Comment by mhadam** [comment]
It seems this is probably specific to an old version of UC Browser (9.8) on Android. UC Browser has supported performance timing API since at least version 11.8.

I'm going change the code to ignore properties in a performance object that are null, since the schema fields are all optional. That should fix this issue.

https://developers.whatismybrowser.com/useragents/parse/197447-uc-browser-android-webkit
https://caniuse.com/#feat=nav-timing
https://github.com/snowplow/iglu-central/blob/master/schemas/org.w3/PerformanceTiming/jsonschema/1-0-0

**Comment by alexanderdean** [comment]
SGTM, thanks @mhadam
