### ISSUE TITLE
Create @snowplow/browser-tracker package for npm distribution

### ISSUE THREAD

**Issue by evgenyrodionov** [snowplow/snowplow-javascript-tracker#541]
Was: *Why not in npm?*

Hey guys, I want bundle your script with webpack, but latest version in npm is 0.2.0. Why?

**Comment by rarkins** [comment]
I'm also surprised if many aren't using this via package management and npm.

A good reference for semantics would be https://www.npmjs.com/package/mixpanel-browser

e.g.

```javascript
var mixpanel = require('mixpanel-browser');
 
mixpanel.init("YOUR_TOKEN");
mixpanel.track("An event");
```

**Comment by alexanderdean** [comment]
> Hey guys, I want bundle your script with webpack, but latest version in npm is 0.2.0. Why?

Hi @evgenyrodionov - the version in npm is the [Snowplow Node.js Tracker](https://github.com/snowplow/snowplow-nodejs-tracker), not this (browser-side) tracker.

@rarkins made a great case for adding the browser-side tracker to npm in #432.

I am renaming this ticket to avoid confusion, and scheduling this into 2.8.0. It may get pushed back a little if it turns out to be complex.

**Comment by alexanderdean** [comment]
Depends on #545

**Comment by mpolichette** [comment]
Is there work we could do on our side to assist with making this an npm module?

**Comment by alexanderdean** [comment]
Hey @mpolichette - thanks for your support! We are not about to kick off work on 2.8.0 (though 2.7.0 is in QA), so any PRs you can share around this functionality would be awesome. Maybe even just a PoC PR with a super-simple `Tracker.track()` that proves out the approach...

**Comment by brandonmp** [comment]
in the mean time, you can [add packages to your project directly from github](http://stackoverflow.com/questions/17509669/how-to-install-nodejs-package-from-github-directly)

**Comment by danny-andrews** [comment]
@alexanderdean I played around with using the browser snowplow-tracker as an npm dependency, and I got it working (almost) without any hiccups. 
My package.json:
```json
"snowplow-tracker": "git+ssh://git@github.com/snowplow/snowplow-javascript-tracker.git#2.8.1",
```

```js
import snowplow from 'snowplow-tracker/src/js/snowplow';

const tracker = new snowplow.Snowplow([], 'myCoolTracker');
```

Only thing that my bundler got tripped up on was:
`Module not found: Error: Can't resolve '../lib_managed/lodash' in 'node_modules/snowplow-tracker/src/js/lib'` since that is built as part of the Grunt build. Two possible solutions for this:
1. Only load the lodash functions you need: `var get = require('lodash/get')`
2. Run the build step as part of a release, and include it in version control.

The only other things you'd need to do is create an `index.js` file and point your `package.json`'s `main` field to it so you can change `import snowplow from 'snowplow-tracker/src/js/snowplow';` to `import snowplow from 'snowplow';`
