### ISSUE TITLE
Explore race conditions with multiple trackers installed on page

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-javascript-tracker#560]
We have at least two users that experience same problem with trackers installed by 3rd side. 

* In both cases 3rd side is http://keywee.co.
* It looks like a race condition and therefore not easily reproducible

Although it looks impossible in current version of tracker, we may want to explore version installed by keywee (2.4.3?)

More info: http://discourse.snowplowanalytics.com/t/strange-js-error-with-javascript-tracker-with-multiple-sp-js-load/1080

**Comment by alexanderdean** [comment]
If the problem is in 2.4.3, then won't this be difficult for us to tackle in a new release from us?

**Comment by chuwy** [comment]
It would, indeed. But we also need to discover a problem to make sure this is in 2.4 and there's still may be a chance we can protect newer trackers.

**Comment by alexanderdean** [comment]
Makes sense, thanks!

**Comment by chuwy** [comment]
One possible culprit in pre-2.6.0 could be this https://github.com/snowplow/snowplow-javascript-tracker/commit/1e59f802aa065c7ae014394b2684d4fd11b42033. But it cannot explain why this happens when different namespaces are used.

**Comment by chuwy** [comment]
If page has two [script tags](https://github.com/snowplow/snowplow-javascript-tracker/blob/1e59f802aa065c7ae014394b2684d4fd11b42033/tags/tag.js#L56) (user's with 2.7.0 and keywee's with 2.4.3), both attaching `script`s with sp.js and pushing namespaces (`user_snowplow` and `keywee_snowplow`) to `GlobalSnowplowNamespace`, is it possible for keywee's 2.4.3 to be loaded first and pop `user_snowplow` namespace?

If that is possible it can explain absence of `trackSelfDescribingEvent` in discourse thread above, but cannot explain keywee's tracker sending events to user's collector.

**Comment by BenFradet** [comment]
@dmpacheco came up with a way to make this bug appear, from his email:

>While doing the QA 2.8.0 RC I have come across a strange behavior with the Javascript tracker.
Having two different versions of the javascript tracker and one tracker instance referencing only one of them can cause the browser to randomly load either version. 
We have created a simple html document to demonstrate our set-up. (attached to the email). 
In the file, we included version 2.7.2 and 2.8.0 and called them T272 and T280 respectively.  We created a tracker instance that would only load T272. 
When testing in Chrome with disable cache both version of the tracker could be loaded when reloading the page multiple times as seen below. 

![image](https://cloud.githubusercontent.com/assets/1737211/25909130/1148f8b8-35a4-11e7-9717-e3f18edce027.png)

[Analytics_test_JS.html.txt](https://github.com/snowplow/snowplow-javascript-tracker/files/990452/Analytics_test_JS.html.txt)

**Comment by alexanderdean** [comment]
Bringing forwards...

**Comment by chuwy** [comment]
Seems that some users are able to resolve this by updating keywee, so likely problem does not manifest itself with newer trackers.

**Comment by paulboocock** [comment]
Fixing the race condition isn't currently possible if we wish to maintain asynchronous loading of an external sp.js file that runs immediately as it loads and not changing the snippet with each release of the tracker. This problem will become less important as we move towards a modular future, where many users will likely `npm install` the tracker into their web app and initialise it within their application (with no need to put anything onto `window`).

Not relying on the same global namespace across different versions would fix it but that would mean with each version of the tracker, creating a new <script> snippet.
If users do wish to run multiple versions on the same page, the easiest fix is the build sp.js from source but change init.js and the <script> snippet to use a different value for the window property "GlobalSnowplowNamespace", so that the two different versions are popping namespaces off different queues.

init.js

```
if (windowAlias.GlobalDifferentNamespace && windowAlias.GlobalDifferentNamespace.length > 0) {
	queueName = windowAlias.GlobalDifferentNamespace.shift();
...
```

snippet

```
<script type="text/javascript" async=1>
    ;(function(p,l,o,w,i,n,g){if(!p[i]){p.GlobalDifferentNamespace=p.GlobalDifferentNamespace||[];
    p.GlobalDifferentNamespace.push(i);p[i]=function(){(p[i].q=p[i].q||[]).push(arguments)
    };p[i].q=p[i].q||[];n=l.createElement(o);g=l.getElementsByTagName(o)[0];n.async=1;
    n.src=w;g.parentNode.insertBefore(n,g)}}(window,document,"script","sp.js","snowplow"));
</script>
```

**Comment by ArcLightSlavik** [comment]
I get the same error (Uncaught TypeError: Cannot read property 'apply' of undefined) when using: `https://d1fc8wv8zag5ca.cloudfront.net/2.5.1/sp.js`

But if i change it to: `https://d1fc8wv8zag5ca.cloudfront.net/2.7.2/sp.js` it works as expected

Full code: 
```
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
    <title>The title</title>
    <script type="text/javascript">
        (function (p, l, o, w, i, n, g) {
            if (!p[i]) {
                p.GlobalSnowplowNamespace = p.GlobalSnowplowNamespace || [];
                p.GlobalSnowplowNamespace.push(i);
                p[i] = function () {
                    (p[i].q = p[i].q || []).push(arguments)
                };
                p[i].q = p[i].q || [];
                n = l.createElement(o);
                g = l.getElementsByTagName(o)[0];
                n.async = 1;
                n.src = w;
                g.parentNode.insertBefore(n, g)
            }
        }(window, document, "script", "https://d1fc8wv8zag5ca.cloudfront.net/2.5.1/sp.js", "snowplow_tracker"));

        snowplow_tracker(function () {
            console.log("sp.js has loaded");
        });

        snowplow_tracker('newTracker', 'cf', 'localhost:8099', {
            appId: 'snowplowTracker',
            platform: 'web',
            contexts: {
                webPage: false,
                performanceTiming: false,
            }
        });

        function track() {
            console.log("normal_function")
            snowplow_tracker('trackSelfDescribingEvent', {
                schema: 'iglu:com.acme_company/viewed_product/jsonschema/2-0-0',
                data: {
                    productId: 'ASO01043',
                    category: 'Dresses',
                    brand: 'ACME',
                    returning: true,
                    price: 49.95,
                    sizes: ['xs', 's', 'l', 'xl', 'xxl'],
                    availableSince: new Date(2013, 3, 7)
                }
            });
            console.log("normal_function_END")
        }
    </script>
</head>

<body>
    <div class="container">
        <button class="event_one" id="event_one" type="button" onclick="track()">Event</button>
    </div>
</body>

</html>
```

Pointing this out since you are using the 2.5.1 version in the docs, here to be specific: https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#36-ad-tracking-methods

Also putting sp.js file for me feels like a much easier approach and i would probably put that in the docs alongside the self-hosting one.
