### ISSUE TITLE
Add Adobe Target context

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#569]
* Add a schema to Iglu Central equivalent to our [Optimizely summary context](https://github.com/snowplow/iglu-central/blob/master/schemas/com.optimizely.snowplow/optimizely_summary/jsonschema/1-0-0)
* Add code sniffing for Target parameters and attaching them to each event if found ([as per for Optimizely](https://github.com/snowplow/snowplow-javascript-tracker/commit/8f2619fa8e0eed0c1eb28c2d952c506fc8ed75e5))

**Comment by paulboocock** [comment]
Closing due to lack of movement or interest. We are considering a plug-in architecture for additional `autocontexts` in v3. This could be achieved via that either by Snowplow or by a contributor who wishes to create an autocontext for their application without increasing the size of our code base and sp.js size.
