### ISSUE TITLE
Make newDocumentTitle variable local

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-javascript-tracker#580]
https://github.com/snowplow/snowplow-javascript-tracker/blob/c67ec2368a3049dfc053291b2d26fd490e20bd48/src/js/tracker.js#L1305

Trying to figure out why it was made global.

**Comment by brightwrite-admin** [comment]
v2.7.2 and 2.8.2. Throws an exception `newDocumentTitle is not defined` now when you use `enableActivityTracking`.

**Comment by brightwrite-admin** [comment]
@chuwy Fixed. I had issues with Safari and Chrome (latest version). I guess it might be last changes in JS engine. enableActivityTracking feature didn't work there.

**Comment by chuwy** [comment]
Hello @brightwrite-admin, I just checked it in both latest Chrome and Safari and `enableActivityTracking` seems to work in both stable versions.

I think it might be problem with one of plugins installed on your browser. Otherwise this indeed can be a quite serious bug.

**Comment by brightwrite-admin** [comment]
Thanks for checking it @chuwy!

I don't think it's an extension, as I don't have any extensions installed in Safari.
What I think causes this problem is the way how I install SnowPlow, it's a WebPack module.
I believe the problem might be in hoisting. It's hard to debug, but changing this var to local fixes the issue. I checked this global var is not used anywhere.
