### ISSUE TITLE
`setReferrerUrl` can't be set to an empty string

### ISSUE THREAD

**Issue by bernardosrulzon** [snowplow/snowplow-javascript-tracker#637]
I'm having trouble with `setReferrerUrl` in cases I need to reset the referrer, i.e. set it to `undefined` or to an empty string.

It basically ignores the setting and uses the previous value. Are there any workarounds?

Thanks!

**Comment by alexanderdean** [comment]
Hmm, need to think about this one...

**Comment by bernardosrulzon** [comment]
Btw, setting it to `undefined` or `null` or `''` yields the same result

**Comment by paulboocock** [comment]
So this issue comes from the fact that we default to the original page referrer unless the value passed to `setReferrerUrl` is truthy. You can set the referrer path to '#' (i.e. `window.snowplow('setReferrerUrl', '#');`) which will lead to blank refr fields in atomic.events. This should be pretty safe as we can't fail events for invalid URLs in the referrer field as we can extract them from Querystrings which could have any old gibberish in them so instead we just don't populate refr fields on invalid refr values. 

I'm not sure I'd want to add the logic in or an additional api method to clear the referrer field as that adds a little bloat to the codebase size that we're trying to avoid.
