### ISSUE TITLE
Add GDPR context

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#645]

**Comment by alexanderdean** [comment]
Depends on https://github.com/snowplow/snowplow-javascript-tracker/issues/405

**Comment by yalisassoon** [comment]
The idea would be to send a GDPR context with every event. It would include the following fields:

* `basisForProcessing`. This would be an enum that could be set to any of the six legal basis for processing i.e. `consent`, `contract`, `legal obligation`, `vital interest`, `public task`, `legitimate interests`
* `documentId`. The ID of a document which details the basis for processing. So if e.g. the basis for processing is `legitimate interest`, that document ID would point to a document that described that legitimate interest. Similarly, if the basis for collection was consent, that document would detail the nature of the consent provided.
* `documentVersion`. The version of the above document.
* `documentDescription`. The description of the above document.

It should be possible to set the values to be included in this global context on initialization, and have methods for changing those methods if e.g. a user a provides consent mid-session. (Thereby changing the `basisForProcessing`.

**Comment by mhadam** [comment]
We should probably transition to using global contexts for standard contexts. But there needs to be some care to segregate standard contexts from other global contexts. The concern being that you can remove all global contexts, and that would wipe away anything you've added (including the standard ones enabled).

So we need these methods on the tracker:
* `tracker.enableGDPRContext(basisForProcessing, documentId, documentVersion, documentDescription)`

^ calling this repeatedly will update the context, but we could otherwise add a third method `updateGDPRContext(...)`

* `tracker.disableGDPRContext()`

This would be a good place to insert tagging functionality into global contexts (shouldn't be lots of work but requires releasing a new version of the core which is good to get familiar with).

Use something like for `basisForProcessing`:
https://www.sohamkamani.com/blog/2017/08/21/enums-in-javascript/#namespaced-enums

**Comment by colmsnowplow** [comment]
@yalisassoon keen for your input two things:

1. Should the values persist?
If my basis at first is 'legitimate interest', but then I am granted consent, presumably we need to persist the consent basis in future (ie for subsequent sessions and page views).

The tracker can either: 
- assume that this is managed externally, and overwrite the values for this context every time it's called (ie the user records basis and passes this to the tracker), 
or 
- persist the latest values, and allow users to choose to 'overwrite value', or 'only set value if it doesn't exist' 

2. Should we handle multiple trackers individually?

The simplest instrumentation is to have all trackers on page share gdprContext values, however one tracker may be a third party with a different basis for processing to the others. 

Thoughts on these?
