### ISSUE TITLE
Prevent empty string values of structured event being cast to null

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-javascript-tracker#662]
```js
snowplow_name_here('trackStructEvent', 'Mixes', 'Play', '', '', "not-a-string");
```

Value will appear as `null` in enriched event (and we see nothing in network tab). Not sure if this is a bug or expected behavior, but at least looks inconsistent with self-described events that will go bad bucket if unexpected type was specified and I couldn't find any explicit conversion.

**Comment by alexanderdean** [comment]
Hmm, that's odd. If this is a bug, it's been around for a very long time.

**Comment by paulboocock** [comment]
So it turns out that Enrich now turns empty strings into null values for Structured Events, so there isn't much point in sending them in the payload (note the failing integration test in the above commit where I expected an empty string but got a null in the enriched event). We don't add empty strings, null or undefined to any of the canonical event fields in the JS tracker so this change would make structured events the odd one out here. I'm going to close it as won't fix, but additionally it wouldn't change the final enriched output anyway and would only lead to more code in the tracker and larger payloads to the collector.
