### ISSUE TITLE
Detecting ad blocker

### ISSUE THREAD

**Issue by szareiangm** [snowplow/snowplow-javascript-tracker#668]
It would be nice if we could detect Ad blocker and have it with page_view event contexts. 

There are many ways and I Googled quickly. This is what I found:
https://www.detectadblock.com/
https://clearcode.cc/blog/detect-ad-blockers/

**Comment by alexanderdean** [comment]
Cool idea!

**Comment by paulboocock** [comment]
Rather than building this directly into the tracker, we would suggest that you implement this yourself using `trackUnstructEvent`. Create a custom schema and implement the ideas in the sites you mention so you can track when ad blockers are present. 
One of the reasons for not implementing this is we want to reduce the codebase size and allow for features to be built on top of the tracker rather than having automatic or built in support.
