### ISSUE TITLE
Improve event flushing options and remove pageUnloadTimer

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#719]
Current value used in combination with automatic link click tracking can slow the loading of subsequent pages on a website, as the timer is enabled after each link click.

**Comment by paulboocock** [comment]
With improvements to Beacon and the local storage queue, it seems reasonable to reduce this. 
Perhaps we should have a set of defaults depending on tracker config:
Using GET and Cookies - stay at 500ms
Using POST and Local Storage - drop to 100ms(?)
Using Beacon - drop to 0ms(?)

Needs considerable testing for event loss.

**Comment by alperakgun** [comment]
>  Using Beacon - drop to 0ms(?)

@paulboocock Thinking about the question mark at the end, what risks could there be using Beacon with a `0ms`  `pageUnloadTimer`?

PS: We have a Post/Localstorage based implementation, where we want to keep the `link_click` events, and have no delay before unloading a page.

**Comment by paulboocock** [comment]
Hey @alperakgun I totally missed this notification, apologies!

In an ideal world, using 0ms with beacon would be the perfect scenario, and it should technically work, but beacon behaves inconsistently across browsers, which is the main cause for me to add the `(?)`. I think you'll be fine but you're trusting the browsers to send events so you might find some browsers don't behave as you would expect (particularly older Safari (10-11ish) and Chrome < v81 (falls back to POST)). I think this is a balancing act, are you happy to lose some events for improved website performance? If so, give it a try and monitor your results over a couple of weeks - I'd strongly advise looking at results grouped by browser to see if you notice any significant changes in events from certain browsers.

**Comment by alperakgun** [comment]
Thanks @paulboocock - it makes sense.

**Comment by paulboocock** [comment]
I've taken a multiple pronged strategy here which allows for the removal of the pageUnloadTimer.

I'm now flushing the buffers on `page vivisilibty -> hidden` events. This means we flush more frequently but works on mobile and desktop. I'm also leaving in the `beforeUnload` flush but with no delay timer (since it doesn't work in modern browsers anyway). To keep the "old browser" functionality, when flushing I'm sending the XHR with the `sync` flag as `true`. Modern browsers ignore this but old browsers likely respect it so should still see beforeUnload flushing work.

I've also extended the flushing options too. You can now set the buffer size using `setBufferSize` meaning if you want to start with a higher buffer size but drop it in your own page unload handling you can do. You can also set an optional property on `flushBuffer` which will lower the buffer size post flushing (handy in scenarios such as those described in #890 and #894).

I've also updated beacon so that the beacon preflight is only required on Safari. This should increase the effectiveness of using `eventMethod: beacon` on all browsers except for Safari <= 13 where beacon is a bit janky (see  #716). We'll now always use post in those older Safari versions.
