### ISSUE TITLE
Reset activity on page view

### ISSUE THREAD

**Issue by asgergb** [snowplow/snowplow-javascript-tracker#750]
If you enable activity tracking in a single page app, activity/heartbeats spans (virtual) page views. In short, we are interested in the time spent on individual pages and not total visit length. Therefore, we would like the user's activity to be reset when we trigger `trackPageView`.

For example, if you set the heartbeat delay to be 30 seconds, and the user spends 15 seconds on page 1 and 15 seconds on page 2, the 30 seconds will be attributed to page 2.

Sample implementation with a config variable to enable the reset: https://github.com/Jyllands-Posten/snowplow-javascript-tracker/commit/0b9e49398d9cb7c5e0052473cd31585043db7365

This also happens to solve a related problem with single page apps where the contexts in the new page view for page 1 are not included in the heartbeats on page 2 because the heartbeats inherit page 1's contexts. In general, you can use the context callback to solve this, however, when using Google Tag Manager, the dataLayer variables are frozen when the first page view is triggered (https://www.simoahava.com/analytics/fetch-latest-value-data-layer-variable/).

**Comment by yalisassoon** [comment]
@asgergb - many thanks for opening this issue.

I _think_ there are a couple of issues on single page apps with our current approach:

1. When you trigger a manual `trackPageView` call to indicate that a virtual page view is fired, the activity tracking does not reset. This means that if the e.g. the page pings are set to fire every 10 seconds, but only after an initial waiting period of 30 seconds, there isn't a 30 second interval after the virtual page view before the first page ping on the new virtual page view fires. (Instead the previous schedule of page pings is maintained based on the last "real" (rather than virtual) page view.
2. The global contexts that are sent with each page view are those inherited from the last "real" page view rather than the last virtual page view, which should be the desired behaviour.

If that's right then the most likely way we'd solve this is to add one or two arguments to the trackPageView methods that would be called from an SPA on firing a virtual page view that:

1. Reset activity tracking
2. Reset the all global contexts

Does that make sense? Want to make sure there isn't an aspect of running Snowplow on a SPA that we're missing?

**Comment by asgergb** [comment]
1. Yes, the schedule depends entirely on the first page view.
2. If by "global" contexts you mean the contexts send to `trackPageView`, yes, the additional page views inherit the first page view's contexts.

Yes, you could also implement this on `trackPageView` instead of `enableActivityTracking`, but it is related to the activity tracking and you probably often have page views without activity tracking enabled, so in that perspective, I think it belongs to `enableActivityTracking`. I will let you guys worry about that detail, though, but I'll be happy to contribute patches.

**Comment by colmsnowplow** [comment]
Same issue, different approach to: https://github.com/snowplow/snowplow-javascript-tracker/issues/717
