### ISSUE TITLE
Change initial page ping to fire at minimum visit length when less than heart beat delay.

### ISSUE THREAD

**Issue by abiswas-tgam** [snowplow/snowplow-javascript-tracker#803]
When the minimum visit length delay is set to smaller than heat beat delay, the first page ping doesn't fire. 

For example: 
snowplow_name_here('enableActivityTracking', 5, 20), won't trigger a page ping after 5 second, only the rest 20s will.

**Comment by paulboocock** [comment]
This is by design but I can see how it is a confusing API. 
The third parameter (`20`) is the heartbeat of the activity tracking, so we only check for activity on that heartbeat. If the first page ping doesn't align with the heartbeat then it will fire on the first heartbeat. 
The idea is that you would use something like `snowplow('enableActivityTracking', 30, 10)`, so you only classify a active page view (i.e. a single page ping) when the user has been active for 30 seconds and then every 10 seconds you check if they are still active to get total active time on page.
As a change, perhaps it would be more useful to fire the first page ping at the minimum visit length delay if it is less than heartbeat (so lower the initial heart beat then raise it to the set heartbeat after the first pulse). 
This is a behaviour change to some extent, rather than a bug, but it seems unlikely to cause issues for anyone as it doesn't currently work as you would probably expect the API to do so and the majority of implementations I've seen use the same value for minimum visit and heart beat. In that case I think we can get this into a Minor release, rather than having to wait for a Major.

**Comment by abiswas-tgam** [comment]
Thanks for the quick reply and putting it in pipeline as minor release!

So, looking at the current version `tracker.js`, I see it doesn't have provision for the use case we have. However, in previous versions (before 2.12.0), it use to work perfectly. No sure, what exact updates caused it to break. 

If the team has started working on this piece, do you have a tentative timeline when can we expect an update? If not, would you like us to offer a solution and open a PR? Either ways works for us. Let us know, if we can make your life any easier. 😊😊

**Comment by paulboocock** [comment]
We did make some changes to activity tracking in 2.13.0 and may have unexpectadly introduced this slight behavior change as a consequence (we added the activity tracking callback and the ability to reset the activity time on page view). However, if we have regressed this, then that certainly wasn't the intention!
The two recent PRs I'm referring to are: https://github.com/snowplow/snowplow-javascript-tracker/pull/766 and https://github.com/snowplow/snowplow-javascript-tracker/pull/779

We're tentatively aiming for the end of April for our next JS tracker release and a PR would be more than welcome!

**Comment by abiswas-tgam** [comment]
Just opened this PR https://github.com/snowplow/snowplow-javascript-tracker/pull/804 for your review. Let me know, if you would like me to alter anything or have any questions. 

Also, I noticed continuous integration is failing not sure why, if there is something we can do to fix also let me know.

**Comment by paulboocock** [comment]
Thanks for the PR! It seems you've bumped into our famous flakey test - hopefully I get a chance to fix that in the next release 😄

**Comment by abiswas-tgam** [comment]
Thanks @paulboocock !!
