### ISSUE TITLE
Not able to use snowplow-tracker-core in angular

### ISSUE THREAD

**Issue by ArcLightSlavik** [snowplow/snowplow-javascript-tracker#809]
I'm trying to enable tracking in angular using the npm package 'snowplow-tracker-core'
But i'm getting this error

`ERROR in ./node_modules/snowplow-tracker-core/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /Users/user/proj/<<project_name>>/node_modules/snowplow-tracker-core/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/user/proj/cart/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:933:23)
    at /Users/user/proj/<<project_name>>/node_modules/@ngtools/webpack/src/loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

and i couldn't get pass this issue in any way.

Is there a different setup process in angular compared to the one given in the readme?

**Comment by paulboocock** [comment]
Unfortunately at the moment we don’t have a version of our JavaScript tracker that is packaged as a module so that you can import in this way. When working on an application of the type you describe (Angular, React, etc), we often see our sp.js file downloaded from GitHub Releases and bundled into applications so that it loads along with the rest of your JavaScript assets. If this isn’t feasible then the best option currently is to take sp.js and host it on a CDN, such as CloudFront, or add it as an app asset, to be loaded asynchronously through the script tag snippet.

**We've built an example Angluar application here where we wrap the Snowplow JavaScript tracker in a service: https://github.com/snowplow-incubator/snowplow-javascript-tracker-examples/tree/master/angular/ngSnowplow**

The good news is that publishing the JavaScript tracker on NPM as a module is on our roadmap for 2020, we certainly want to look at how we can better bundle our JavaScript tracker and this will form part of it. You could subscribe to this Github issue to get updates once we begin our work on it. This issue will certainly form part of the work towards this goal: https://github.com/snowplow/snowplow-javascript-tracker/issues/752.

As for the NPM Package `snowplow-tracker-core` you mentioned, this is the shared core between our JavaScript tracker and Node.js tracker. It doesn’t include a number of features that the Tracker libraries contain, such as a variety of helper tracking functions and utilising Local Storage to cache events on page change or poor connectivity. We generally advise to not directly use this, unless you wish to build your own wrapper and tracking functionality around the core Snowplow tracking library.

**Comment by ArcLightSlavik** [comment]
The example app was exactly what i was looking for
Thanks 😄
