### ISSUE TITLE
A big lag between dvce_created_tstamp and dvce_sent_tstamp

### ISSUE THREAD

**Issue by greg-md** [snowplow/snowplow-javascript-tracker#885]
**Describe the bug**
Can someone explain that big lag between `dvce_created_tstamp` and `dvce_sent_tstamp`? Or maybe there is a bug under specific circumstances?

Is there a way to change how `derived_tstamp` is calculated?

| dvce_created_tstamp     | dvce_sent_tstamp        | collector_tstamp        | derived_tstamp          |
|-------------------------|-------------------------|-------------------------|-------------------------|
| 2019-01-19 21:47:05.464 | 2021-01-12 15:32:55.515 | 2021-01-12 15:32:56.293 | 2019-01-19 21:47:06.242 |
| 2019-01-31 07:36:40.405 | 2021-01-12 17:46:53.331 | 2021-01-12 17:46:54.305 | 2019-01-31 07:36:41.379 |
| 2019-02-17 00:46:50.466 | 2021-01-12 18:40:53.06  | 2021-01-12 18:40:53.428 | 2019-02-14 00:46:50.834 |
| 2019-02-17 00:47:35.693 | 2021-01-12 18:40:53.35  | 2021-01-12 18:40:53.556 | 2019-02-14 00:47:35.899 |
| 2019-02-17 00:47:59.14  | 2021-01-12 18:40:53.518 | 2021-01-12 18:40:53.718 | 2019-02-14 00:47:59.34  |
| 2019-02-17 00:47:59.277 | 2021-01-12 18:40:54.916 | 2021-01-12 18:40:55.114 | 2019-02-14 00:47:59.475 |

**To Reproduce**
Not sure how to reproduce

**Expected behavior**
The difference between `dvce_created_tstamp` and `dvce_sent_tstamp` should be minimal for live, browser apps.

**Comment by paulboocock** [comment]
This is quite common if you are using local storage within the tracker (which is the default setting). If the event fails to send then it is queued back into the tracker without the `dvce_sent_tstamp` as this is added at the last possible moment before sending. Events can fail to send for a number of reasons, collector being unavailable, collector returning a 500 error code (rare but possible particularly when under heavy load), poor internet connectivity, user navigating before request completes.

When the user then next visits a page with the same Snowplow tracker on it, it will try to send the event again. This is what leads to the big discrepancy between `dvce_created_tstamp` and `dvce_sent_tstamp`. The `derived_tstamp` is a timestamp that is a best guess of roughly when the event occured, in the case of a big gap between `dvce_created_tstamp` and `collector_tstamp` you'll find it uses the `dvce_created_tstamp`. There is no way to change this, thats simply how we calculate the `derived_tstamp` and it is something done by the pipeline rather than the tracker.

If order of event arrival is important, then using `collector_tstamp` is probably the best timestamp. If you want to know when the event _probably_ occured for the user, then `derived_tstamp` is likely a better choice.

I hope that helps you understand where the differences in those timestamps can come from.
