### ISSUE TITLE
"Late to the Party" bug during `beforeunload` browser teardown

### ISSUE THREAD

**Issue by ScottyMJacobson** [snowplow/snowplow-javascript-tracker#890]
Hello all! Good to be back in the repo - really exciting to see how actively you're maintaining it, and hope I can contribute positively again.

**Describe the bug**
In response to a window `beforeunload` event, the snowplow singleton [runs all the `bufferFlushers`](https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/snowplow.js#L118). A `OutQueueManager`'s `bufferFlusher` [sends out everything it has in its buffer so far](https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/out_queue.js#L129). However, depending on the order of a user's `beforeunload` handler, or if they're using an event that comes after `beforeunload` (it's not clear to me where `pagehide` happens), they might then track their relevant event (in Eko's use case, it's called `dropoff`) _after_ this flush has happened. Basically, they're too late to the party, and just get queued, and will _maybe_ get sent the next time around the next time the user navigates to a page and it gets loaded from the localStorage queue.

**To Reproduce**
*(**edit:** Set buffer > 1, and)* attach a `beforeunload` handler that runs after snowplow tracker's. `snowplow('trackStructEvent', 'dropoff')` within that handler. It will get queued rather than sent out; you'll see it in the queue when you refresh the page. Sorry I don't have my reproduction page for this anymore. Happy to make one if it helps.

**Expected behavior**
I would hope that snowplow sort of goes into "send them out!" mode and immediately attempts to send out any more events it receives to a tracker after flushing its buffer. This sort of breaks an abstraction, but if it, for instance, [sets the bufferSize to 1 once it has flushed the buffers](https://github.com/ScottyMJacobson/snowplow-javascript-tracker/commit/b566f16ec877d4a8dfedfe7f302cdb91eb74552e), sort of disabling the buffers after the fact, that will do the trick. Would be happy to take this same commit and make a pull request on top of the current codebase 🙂.

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Chrome
 - Version 88

**Comment by paulboocock** [comment]
Welcome back @ScottyMJacobson 

Interesting problem you have there, `pagehide` does indeed fire straight after `beforeunload`. I think it's quite an interesting use case to think about what we could do when an event is fired after we've technically decided we're done on this page now.

![image](https://user-images.githubusercontent.com/8820009/107339797-03c81080-6ab5-11eb-909f-a4824d0e91c6.png)

Your solution to try to fire the events as a last ditch attempt seems reasonable - although I think I'd expect the tracker to try and send the event anyway with a bufferSize set to 1 (which we always recommend to reduce the chance of missing events). From what I've observed, many browsers don't wait around for http requests to complete in these late page lifecycle handlers so I'm not sure how much luck you would have trying to send it out at the last second using POST or GET.

One workaround would be to try and switch to `beacon` and if that isn't desirable for all events then maybe [create a second tracker on the page](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-tracker/general-parameters/managing-multiple-trackers/) with identical parameters but that uses `beacon`. This will complicate the instrumentation of the tracker on the site (as you'll have two trackers everywhere and you'll need to pick the right one else it'll send twice) but it would be interesting to see how it behaves (particularly because beacon doesn't behave that well on mobile in `beforeunload` and `unload`, so we generally advise to fire in `visibilitychange` but I don't think that will work for what you describe).

I'd be open to a PR on this but we're deep into a refactor for v3 now and it'll be challenging to include a PR for this in v3 that is built on top of the v2 codebase. The v3 branch isn't particularly stable yet either but should be soon, I'll let you know when that is (probably 7-14 days).

**Comment by ScottyMJacobson** [comment]
Thanks for the detailed response @paulboocock! - where'd you get that diagram?

I'm realizing I left some gaps in my description about the tracker we're using - sorry about that! 

1) Our tracker actually is configured to use a `bufferSize` of 10 to try to reduce the extra requests we send out due to tracking. Interesting to know you advice using a `bufferSize` of 1; I definitely could see the argument for doing that but we send a lot of events so it seemed prudent to bundle them. Could you point me to where in your documentation you make that recommendation so I can share that with the team? But yeah, I think this is a crucial detail I left out as to why our subsequent events are buffered.

2) The tracker also uses beacon - so, though standard GET and POST are almost certain to get cut off and fail, we've had success with the patch I sent you where `bufferSize` is forced to 1 after the buffer is cleared, and the tracker sends this event via beacon as soon as it gets it.

Re: your sometimes-beacon approach - that's actually what we do on iOS to avoid the russian roulette of beacon issues on non-dropoff events. On the rest of browsers, we're comfortable sending all requests via beacon - would there ever be a reason not to?

(And this refactor is exciting news! Can't wait to see the outcome - must feel nice and I'll look at any obvious places to contribute - gotten a lot of use out of the tracker over the last few years!)

**Comment by paulboocock** [comment]
> On the rest of browsers, we're comfortable sending all requests via beacon - would there ever be a reason not to?
Not really, Safari is the main culprit for dodgy Beacon data although it seems mostly resolved in Safari 13+. We also made some adjustments in 2.14.0 by forcing a POST preflight for Beacon to help Safari out (since it fails for CORS reasons).

As for the buffer size, we mainly discuss it in the docs [here](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-tracker/general-parameters/initializing-a-tracker-2/#POST_support). One thing that does come to mind is forcing a flush in your `pagehide` event handler might work? So after you track the event, immediately call `snowplow('flushBuffer')`.

**Comment by paulboocock** [comment]
> where'd you get that diagram?

https://developers.google.com/web/updates/2018/07/page-lifecycle-api#overview_of_page_lifecycle_states_and_events

**Comment by ScottyMJacobson** [comment]
#894 implements the fix we've been running in our fork since we discovered this behavior - forcing `bufferSize` to 1 once teardown is happening and the buffers are flushed. I'm about to ship a build of our tracker with this fix to a staging env, hoping a colleague will get a chance to do some additional testing in some time during the day tomorrow GMT - I'll loop back

Thank you for pointing at the docs! Making a note internally to reassess our `bufferSize` setting.

_(And sorry for all the GitHub noise ^ - got some weird merge artifacts since our forks were so out of date, but sorted out now as far as the PR is concerned)_

**Comment by paulboocock** [comment]
I've done some testing of the PR and added my feedback to the PR. I have no issue with the change as it is innocent enough but I'm not convinced it works like you'd hoped for this issue.
