### ISSUE TITLE
3.0.0-beta.1 - newTracker expects an absolute collector URL

### ISSUE THREAD

**Issue by talbct** [snowplow/snowplow-javascript-tracker#930]
**Describe the bug/steps**
`newTracker('...', '/track').trackPageView();` tries to send a request to `http://track/...` rather than to the same origin with a `/track` path.

**Expected behavior**
Support relative URLs (first party tracking).

**Desktop (please complete the following information):**
 - OS: macOS 11.1
 - Chrome
 - 89

**Comment by paulboocock** [comment]
The endpoint parameter should be the endpoint of the collector, rather than the path to send the events to.

To do what you are describing, you're going to want to use the Post Path configuration. I've assumed you're running your collector on the same host based on your description (`window.location.hostname`).

```
newTracker('sp1', window.location.hostname, { 
  appId: 'my-app', 
  postPath: '/track'
})

trackPageView();
```

Additionally, you don't need to use the returned BrowserTracker from newTracker, the library keeps module level instances. The only reson to use the return is if you want to get values from the tracker, such as `getDomainUserId()`.
